---
- name: Set git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Set default branch name for new repos
  community.general.git_config:
    name: init.defaultbranch
    scope: global
    value: "{{ git_default_branch }}"
